# Shared parameters used across all pipelines.

# split date
split_date: "2025-07-01"

# Data splits by years
reference_years:
  - 2024
analysis_years:
  - 2025
modeling_years:
  - 2024
  - 2025
drift_years:
  - 2026

# Feature store 
# when Hopsworks credentials are configured in conf/local/ -> set to TRUE
to_feature_store: false

# MLflow tracking
mlflow_tracking_uri: sqlite:///mlflow.db
mlflow_experiment_name: green_taxi_tip_amount
mlflow_registered_model_name: green_taxi_regressor
